export {default as Display} from './Display'
export {default as Create} from './Create'
export {default as Update} from './Update'
export {default as NavBar} from './NavBar'
export {default as Home} from './Home'