version: 2.1
orbs:
  docker: circleci/docker@1.5.0

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run:
          name: define docker tag
          working_directory: "devops/02\ -\ dockerfile"
          command: |
            SHORT_COMMIT_ID=$(git rev-parse --short "${CIRCLE_SHA1}")
            IMAGE_TAG="0.$CIRCLE_BUILD_NUM-$SHORT_COMMIT_ID"
      - docker/build:
          path: "devops/02\ -\ dockerfile"
          image: accuratiorem/flaskapp
          tag: $IMAGE_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: accuratiorem/flaskapp
          tag: $IMAGE_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  commit:
    jobs:
      - build-and-push:
          context:
            - dockerhub-creds
          filters:
            branches:
              only: main
