version: 2.1
orbs:
  docker: circleci/docker@1.5.0

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          path: "devops/02\ -\ dockerfile"
          image: accuratiorem/flaskapp
          tag: version.$CIRCLE_SHA1
      - docker/push:
          digest-path: /tmp/digest.txt
          image: accuratiorem/flaskapp
          tag: version.$CIRCLE_SHA1
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  commit:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: main
