replicaCount: 1

image:
  repository: edvegas/flaskapp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

secrets:
  dbpassword: ZGV2cGFzc3dvcmQ=
  appsecretkey: U3VwZXJTZWNyZXRLZXk=

serviceAccount:
  create: true
  name: edvegas-app

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: flaskapp.local
      paths: 
        - /
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi
