version: '3.8'
services:
  db:
    image: "postgres:9.6.5"
    volumes:
      - "dbdata-${ENVIRON}:/var/lib/postgresql/data/"
    env_file:
      - env_file.${ENVIRON}
  flaskapp:
    image: "flaskapp"
    env_file:
      - env_file.${ENVIRON}
  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
volumes:
  dbdata-dev:
  dbdata-stg:
